services:
  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'
    networks:
      - microservice-net

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c \
                'kafka-topics --create --topic stats.user-actions.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic stats.events-similarity.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092'"
    init: true
    networks:
      - microservice-net

  discovery-server:
    build: infra/discovery-server
    image: discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 20s
    networks:
      - microservice-net

  config-server:
    build: infra/config-server
    image: config-server
    container_name: config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 20s
    networks:
      - microservice-net

  gateway-server:
    build: infra/gateway-server
    image: gateway-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 20s
    networks:
      - microservice-net

  user-service:
    build: core/user-service
    image: user-service
    container_name: user-service
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      user-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=user_service
      - SPRING_DATASOURCE_PASSWORD=user_password
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
    networks:
      - microservice-net

  user-db:
    image: postgres:16.1
    container_name: user-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=user_service
      - POSTGRES_PASSWORD=user_password
      - POSTGRES_DB=user_db
    volumes:
      - ./core/user-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - microservice-net

  event-service:
    build: core/event-service
    image: event-service
    container_name: event-service
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      event-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-db:5432/event_db
      - SPRING_DATASOURCE_USERNAME=event_service
      - SPRING_DATASOURCE_PASSWORD=event_password
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
    networks:
      - microservice-net

  event-db:
    image: postgres:16.1
    container_name: event-db
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_USER=event_service
      - POSTGRES_PASSWORD=event_password
      - POSTGRES_DB=event_db
    volumes:
      - ./core/event-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - microservice-net

  request-service:
    build: core/request-service
    image: request-service
    container_name: request-service
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      request-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://request-db:5432/request_db
      - SPRING_DATASOURCE_USERNAME=request_service
      - SPRING_DATASOURCE_PASSWORD=request_password
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
    networks:
      - microservice-net

  request-db:
    image: postgres:16.1
    container_name: request-db
    ports:
      - "6546:5432"
    environment:
      - POSTGRES_USER=request_service
      - POSTGRES_PASSWORD=request_password
      - POSTGRES_DB=request_db
    volumes:
      - ./core/request-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - microservice-net

  comment-service:
    build: core/comment-service
    image: comment-service
    container_name: comment-service
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      comment-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://comment-db:5432/comment_db
      - SPRING_DATASOURCE_USERNAME=comment_service
      - SPRING_DATASOURCE_PASSWORD=comment_password
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
    networks:
      - microservice-net

  comment-db:
    image: postgres:16.1
    container_name: comment-db
    ports:
      - "6547:5432"
    environment:
      - POSTGRES_USER=comment_service
      - POSTGRES_PASSWORD=comment_password
      - POSTGRES_DB=comment_db
    volumes:
      - ./core/comment-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - microservice-net

  collector:
    build: stats/collector
    image: stats-collector
    container_name: stats-collector
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
      - stats.collector.kafka.server=kafka:29092
      - eureka.instance.ip-address=collector
    networks:
      - microservice-net

  aggregator:
    build: stats/aggregator
    image: stats-aggregator
    container_name: stats-aggregator
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
      - stats.aggregator.kafka.bootstrap-server=kafka:29092
    networks:
      - microservice-net

  analyzer:
    build: stats/analyzer
    image: stats-analyzer
    container_name: stats-analyzer
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      analyzer-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://analyzer-db:5432/stats_db
      - SPRING_DATASOURCE_USERNAME=stats_service
      - SPRING_DATASOURCE_PASSWORD=stats_password
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
      - stats.analyzer.kafka.bootstrap-server=kafka:29092
    networks:
      - microservice-net

  analyzer-db:
    image: postgres:16.1
    container_name: analyzer-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=stats_service
      - POSTGRES_PASSWORD=stats_password
      - POSTGRES_DB=stats_db
    volumes:
      - ./stats/analyzer/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - microservice-net

networks:
  microservice-net:
    driver: bridge